#!/bin/bash

# Get the directory of the current script
SCRIPT_DIR=$(dirname "$(realpath "$0")")


docker compose -f ${SCRIPT_DIR}/docker-compose.yaml up -d
docker compose  -f ${SCRIPT_DIR}/docker-compose.yaml \
   ps --format "table {{.ID}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}\t{{.Names}}"
