spring:
  application:
    name: observation-api
    group: instrumentation
    version: 1.0.0
  jpa:
    open-in-view: true

management:
  observations:
    enable:
      quote: false

  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      encoding: json
      export:
        enabled: true
