server:
  port: 8080

management:
  observations:
    key-values:
      "service.name" : "monolith-ui-api-db"
      region: "us-east-1"
      stack: "prod"
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:15432/quotes"
    username: postgres
    password: password
  jpa:
    open-in-view: false
