spring:
  application:
    name: traces-to-tempo
    group: config
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
      encoding: json
      export:
        enabled: true
