spring:
  application:
    name: traces-to-otel
    group: config
    version: 1.0.0
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
      export:
        enabled: true

#
# need to set this so that the service.name shows up in tempo
#
otel:
  resource:
    attributes:
      service.name: ${spring.application.name}
