spring:
  application:
    name: metrics-to-otel
    group: config
    version: 1.0.0
  jpa:
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    # the tags below are added automatically to the all metrics exported
    # to prometheus
    tags:
      service_name: ${spring.application.name}
      service_group: ${spring.application.config}
      service_version: ${spring.application.version}
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 5s
        enabled: true
        base-time-unit: seconds
