spring:
  datasource:
    url: "jdbc:postgresql://127.0.0.1:15432/quotes"
    username: postgres
    password: password
  jpa:
    open-in-view: false
  application:
    name: monolith-otel-monolith # written to logs as service.name
    group: foo # turns into a tag a way to group related microservices observations together
    version: 1.0.0 # written to logs as service.version

logging:
  file:
    name: logs/micrometer-otel-monolith.log
  structured:
    ecs:
      service:
        environment: dev # per service settings that land in the logs
        node-name: laptop # per service setting that lands in the log
        # name: not needed defaults to spring.application.name
        # version: not needed maps to spring.application.version
    format:
      # console: ecs
      file: ecs
    level:
      io:
        opentelemetry:
          exporter:
            otlp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  observations:
    key-values:
      key: "value"
      location: "laptop"
  tracing:
    sampling:
      probability: 1.0  # Always sample traces in dev
    enabled: true
  metrics:
    tags:
      foo: bar
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
      export:
        enabled: true
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 5s
        enabled: true
        base-time-unit: seconds

